<?php

/** 
 ** Implementation of hook_form_profile2_PROFILE_NAME_alter to make appropriate fields 
 ** only visible and required if bda pref is selected.
 ** (see modules/profile2/profile2.api.php)
 **/
function BDW_bda_conditional_fields_form_profile2_edit_boondocking_available_form_alter(&$form, &$form_state) {
  $bda_input_string = ':input[name="profile_boondocking_available[field_ba_bda_pref][und]"]';
  $dep_if_bda_visible = array('visible' => array($bda_input_string => array('value' => '0')));
  $dep_if_nobda_visible = array('visible' => array($bda_input_string => array('value' => '1')));

  // Got this idea from http://www.deckfifty.com/blog/2012-11/drupal-form-api-conditional-fields

  foreach ($form['profile_boondocking_available'] as $fieldname => &$value)
  {
    switch ($fieldname) {
      case 'field_ba_description':
      case 'field_boondock_location':
      case 'field_ba_photo':
      case 'field_ba_local_attractions':
      case 'field_ba_max_nights':
      case 'field_ba_max_rv_length_int':
      case 'field_ba_number_of_spots':
      case 'field_ba_pets_welcome':
      case 'field_ba_pullthrough_spot':
      case 'field_ba_slideout_awning':
      case 'field_ba_wifi_available':
      case 'field_barbecues_allowed':
      case 'field_generators_allowed':
      case 'field_lawn_chairs_allowed':
        // Hide this field if no bda is selected
        $value['#states'] = $dep_if_bda_visible;
        // Add process callbacks to unrequire this field if bda is not specified
        $value['#process'][] = 'BDW_bda_conditional_fields_if_no_bda_unrequire';
        break;
      case 'field_ba_why_no_bda':
        // hide the 'why no bda' field if bda is selected       
        $value['#states'] = $dep_if_nobda_visible;
        // Add process callback to unrequire this field of bda is specified
        $value['#process'][] = 'BDW_bda_conditional_fields_if_bda_unrequire';
        break;
    }
  }
}

/* implement hook_field_group_build_pre_render_alter to hide the empty fieldset */
// Got this idea from http://stackoverflow.com/questions/11042523/conditional-fieldgroups-fieldsets-in-drupal-7

function BDW_bda_conditional_fields_field_group_build_pre_render_alter(&$element)
{
  $bda_input_string = ':input[name="profile_boondocking_available[field_ba_bda_pref][und]"]';
  $dep_if_bda_visible = array('visible' => array($bda_input_string => array('value' => '0')));

  if (isset($element['group_ba_details']))
  {
    $element['group_ba_details']['#states'] = $dep_if_bda_visible;
  }
}

function BDW_bda_conditional_fields_if_no_bda_unrequire($element, &$form_state) 
{
  if (isset($form_state['input']['profile_boondocking_available']) &&
     $form_state['input']['profile_boondocking_available']['field_ba_bda_pref']['und'] == 1)
  {
    _BDW_bda_conditional_fields_unrequire_element($element);
  }
  return $element;
}

function BDW_bda_conditional_fields_if_bda_unrequire($element, &$form_state) 
{
  if (isset($form_state['input']['profile_boondocking_available']) &&
     $form_state['input']['profile_boondocking_available']['field_ba_bda_pref']['und'] == 0)
  {
    _BDW_bda_conditional_fields_unrequire_element($element);
  }
  return $element;
}

function _BDW_bda_conditional_fields_unrequire_element(&$element)
{
    $element['und'][0]['#required'] = 0;
    $element['und']['#required'] = 0;
}

function BDW_bda_conditional_fields_form_profile2_edit_profile_form_alter(&$form, &$form_state) {
  $form['#validate'][] = 'BDW_bda_conditional_fields_validate';

  foreach ($form['profile_profile'] as $fieldname => &$value) {
    switch ($fieldname) {
      case 'field_escapee_member_data':
      case 'field_rvillage_member_data':
      case 'field_fmca_member_data':
        preg_match('/^(.*)_data/', $fieldname, $matches);
        if (isset($matches[1]))
        {
          $trigger_field = $matches[1];
          $input_string = ':input[name="profile_profile[' . $trigger_field . '][und]"]';
          $value['#states'] = array(
            'visible' => array(
              $input_string => array('checked' => TRUE),
              ),
            'required' => array(
              $input_string => array('checked' => TRUE)
              ),
            );
        }
        break;
    }
  }
}

function BDW_bda_conditional_fields_validate($form, &$form_state) {
  $membership_fields = array(
    'field_escapee_member' => 'Please enter your SKP number', 
    'field_rvillage_member' => 'Please enter your RVillage user name', 
    'field_fmca_member' => 'Please enter your FMCA membership number',
  );
  foreach ($membership_fields as $fieldname => $error) {
    $datafield = $fieldname . '_data';
    if ($form_state['input']['profile_profile'][$fieldname]['und'] == 1 &&
        empty($form_state['input']['profile_profile'][$datafield]['und'][0]['value']))
    {
      form_set_error($datafield, t('@error', array('@error' => $error)));
    }
  }
}
